---

- name: Set root user password
  ansible.builtin.user:
    name: root
    password: "{{ users_root_password | ansible.builtin.password_hash('sha512', users_root_password_salt) }}"
  when: not users_root_password_is_hashed and users_root_password is defined

- name: Set pre-hashed root user password
  ansible.builtin.user:
    name: root
    password: "{{ users_root_password }}"
  when: users_root_password_is_hashed and users_root_password is defined

- name: Create ssh directory for root
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Install authorized_keys file for root
  ansible.builtin.template:
    src: root/.ssh/authorized_keys.j2
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600
